[VALD_CONFIG]
client_id = "nx46BPhS92F0rl8w=="
client_secret = "7daFiGniBsGY7QGSKS41cbSuNlr0bZpfQ="
token_url = "https://security.valdperformance.com/connect/token"
profiles_base_url = "https://prd-use-api-externalprofile.valdperformance.com"
forcedecks_base_url = "https://prd-use-api-extforcedecks.valdperformance.com"
tenant_id = "c6adb3ad-fc33-4ff2-9caf-0a62f254a14e"